### ISSUE TITLE
Disable formatting invalid documents

### ISSUE THREAD

**Issue by Fogapod** [tamasfe/taplo#144]
```toml
[dependencies]
futures = { version = "0.3.15", features = {"executor"] }
```
```toml
[dependencies]
futures = { version = "0.3.15", features = =["executor"] }
```
both produce
```js
[Info  - 6:13:30 PM] Connection to server got closed. Server will restart.
[Error - 6:13:30 PM] Request textDocument/formatting failed.
Error: Connection got disposed.
	at Object.dispose (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:5570:27)
	at Object.dispose (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:11022:35)
	at LanguageClient.handleConnectionClosed (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:13372:42)
	at LanguageClient.handleConnectionClosed (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:16276:15)
	at closeHandler (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:13359:18)
	at CallbackList.invoke (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3569:39)
	at Emitter.fire (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3631:36)
	at closeHandler (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:4783:26)
	at CallbackList.invoke (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3569:39)
	at Emitter.fire (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3631:36)
	at IPCMessageReader.fireClose (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3780:27)
	at ChildProcess.<anonymous> (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:5720:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/server.js:81
    throw up;
    ^

RuntimeError: unreachable
    at <anonymous>:wasm-function[2096]:0x374582
    at <anonymous>:wasm-function[2866]:0x38a73c
    at <anonymous>:wasm-function[2816]:0x389e9d
    at <anonymous>:wasm-function[2865]:0x38a70f
    at <anonymous>:wasm-function[108]:0xd820a
    at <anonymous>:wasm-function[701]:0x2bfefc
    at <anonymous>:wasm-function[189]:0x1810a8
    at <anonymous>:wasm-function[86]:0x81993
    at <anonymous>:wasm-function[3116]:0x38c25c
    at <anonymous>:wasm-function[99]:0xbab2f
[Info  - 6:13:52 PM] Connection to server got closed. Server will restart.
[Error - 6:13:52 PM] Request textDocument/formatting failed.
Error: Connection got disposed.
	at Object.dispose (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:5570:27)
	at Object.dispose (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:11022:35)
	at LanguageClient.handleConnectionClosed (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:13372:42)
	at LanguageClient.handleConnectionClosed (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:16276:15)
	at closeHandler (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:13359:18)
	at CallbackList.invoke (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3569:39)
	at Emitter.fire (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3631:36)
	at closeHandler (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:4783:26)
	at CallbackList.invoke (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3569:39)
	at Emitter.fire (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3631:36)
	at IPCMessageReader.fireClose (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:3780:27)
	at ChildProcess.<anonymous> (/home/eugene/.local/share/vscode/extensions/tamasfe.even-better-toml-0.14.2/dist/extension.js:5720:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

**Comment by tamasfe** [comment]
Currently the formatter is invoked even on syntactically invalid documents, the old formatter could handle partially-valid documents to some extent, the new one doesn't (yet).

We should disable formatting for invalid TOML in the vscode extension.
