### ISSUE TITLE
segfault in docker image

### ISSUE THREAD

**Issue by Hnasar** [tamasfe/taplo#305]
I started the docker image with:

```sh
docker run   --mount type=bind,source="$(pwd)",target=/app  -it --entrypoint /bin/sh tamasfe/taplo
```

and am trying to lint my files, but it repeatedly segfaults on any file I give it:

```
/app # taplo lint pyproject.toml
Segmentation fault
```

(`taplo -h` doesn't segfault though)

Perhaps related to #233 ?

I've uploaded the coredump here:
[docker-taplo-coredump.zip](https://github.com/tamasfe/taplo/files/9418675/docker-taplo-coredump.zip)

----

```
/app # apk add gdb
/app # gdb taplo docker-taplo.coredump
GNU gdb (GDB) 11.2
Reading symbols from taplo...
(No debugging symbols found in taplo)
Core was generated by `/usr/bin/taplo lint pyproject.toml'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (LWP 7331)]
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007f3b65c1c6ce in native_tls::TlsConnectorBuilder::build ()
#2  0x00007f3b65d3066a in reqwest::async_impl::client::ClientBuilder::build ()
#3  0x00007f3b65e88467 in <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll ()
#4  0x00007f3b65e9f38c in taplo::main ()
#5  0x00007f3b65e0f4c3 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#6  0x00007f3b65e10a09 in std::rt::lang_start::{{closure}} ()
#7  0x00007f3b65d7f48c in std::rt::lang_start_internal ()
#8  0x00007f3b65ea00e2 in main ()
```

**Comment by tamasfe** [comment]
Thanks, It seems to have been caused by openssl, which was removed as a dependency in #302.

I haven't done any releases since, but I'm planning to do one this week after some bugfixing.
