### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by prokie** [tamasfe/taplo#371]
Hello!

Is it possible to set a setting so it does not try to open https://www.schemastore.org/api/json/catalog.json on launch. I am trying to use this extension at work, where I do not have internet access.

I am using local schemas so I don't need schemas from that catalog. 

```

WARN initialize:initialize: failed to fetch catalog error=error sending request: JsValue(LA: request to https://www.schemastore.org/api/json/catalog.json failed, reason: connect ETIMEDOUT 20.42.128.105:443
LA: request to https://www.schemastore.org/api/json/catalog.json failed, reason: connect ETIMEDOUT 20.42.128.105:443
    at ClientRequest.<anonymous> (/home/ethopon/.vscode/extensions/tamasfe.even-better-toml-0.19.0/dist/server.js:12:15885)
    at ClientRequest.emit (node:events:526:28)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21))

Caused by:
    JsValue(LA: request to https://www.schemastore.org/api/json/catalog.json failed, reason: connect ETIMEDOUT 20.42.128.105:443
    LA: request to https://www.schemastore.org/api/json/catalog.json failed, reason: connect ETIMEDOUT 20.42.128.105:443
        at ClientRequest.<anonymous> (/home/ethopon/.vscode/extensions/tamasfe.even-better-toml-0.19.0/dist/server.js:12:15885)
        at ClientRequest.emit (node:events:526:28)
        at TLSSocket.socketErrorListener (node:_http_client:442:9)
        at TLSSocket.emit (node:events:526:28)
        at emitErrorNT (node:internal/streams/destroy:157:8)
        at emitErrorCloseNT (node:internal/streams/destroy:122:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:83:21)) self.root=file:///proj/asic_no_backup_trixie1_0/workspaces/ethopon/beetle_subsystem1_0
ERROR initialize:initialize: failed to add schemas from catalog error=error sending request: JsValue(LA: request to https://www.schemastore.org/api/json/catalog.json failed, reason: connect ETIMEDOUT 20.42.128.105:443
LA: request to https://www.schemastore.org/api/json/catalog.json failed, reason: connect ETIMEDOUT 20.42.128.105:443
    at ClientRequest.<anonymous> (/home/ethopon/.vscode/extensions/tamasfe.even-better-toml-0.19.0/dist/server.js:12:15885)
    at ClientRequest.emit (node:events:526:28)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)) self.root=file:///proj/asic_no_backup_trixie1_0/workspaces/ethopon/beetle_subsystem1_0
```

**Comment by jaybuidl** [comment]
+1

**Comment by prokie** [comment]
Have there been any work of late to support local schemas?

**Comment by ia0** [comment]
The project is currently in maintenance mode. So any change would need the help from a contributor.
