### ISSUE TITLE
Code does not support "$ref" tags

### ISSUE THREAD

**Issue by Jeff-Lowrey** [tamasfe/taplo#635]
If I have an OpenAPI document that uses a "$ref" tag, I get the following error:
```
Traceback (most recent call last):
  File "<my_code>\build_openapi_client.py", line 12, in <module>
    document = parse_openapi(url_or_path='../xyz_api.json')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\simple_openapi_client\parser.py", line 20, in parse_openapi
    return Document(**content)
           ^^^^^^^^^^^^^^^^^^^
  File "<string>", line 6, in __init__
  File ".venv\Lib\site-packages\simple_openapi_client\openapi\document.py", line 
18, in __post_init__
    self.paths = {k: Path(**v) for k, v in self.paths.items()}
                     ^^^^^^^^^
  File "\.venv\Lib\site-packages\simple_openapi_client\openapi\path.py", line 140, in __init__
    self.operations[operation_name] = Operation(**operation_data)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 13, in __init__
  File "...\.venv\Lib\site-packages\simple_openapi_client\openapi\path.py", line 114, in __post_init__
    self.parameters = [Parameter(**p) for p in self.parameters]
                       ^^^^^^^^^^^^^^
TypeError: Parameter.__init__() got an unexpected keyword argument '$ref'
```
I am unable to tell which reference it is failing at. My schema has references to both the same file and external files

**Comment by panekj** [comment]
That's not a taplo issue, we do not use Python.
