### ISSUE TITLE
LSP Crashes when Editing Cargo.toml

### ISSUE THREAD

**Issue by Kynson** [tamasfe/taplo#98]
Hi, I have encountered an issue when I try to edit my Cargo.toml. 

When I try to edit a key, the LSP keep crashing, and after it crashes several times the auto-complete simply stops working.

Note: this issue does not exist when editing the `[dependencies]` and `[dev-dependencies]` key

### Video:
https://user-images.githubusercontent.com/46522440/114119002-60f90a80-991c-11eb-9484-82b3ff785107.mov

### Debug output:
<pre><code>
/Users/user/.vscode/extensions/tamasfe.even-better-toml-0.12.0/dist/server.js:81
    throw up;
    ^

RuntimeError: unreachable
    at <anonymous>:wasm-function[2121]:0x37d378
    at <anonymous>:wasm-function[2838]:0x392fe6
    at <anonymous>:wasm-function[2874]:0x393657
    at <anonymous>:wasm-function[2773]:0x3922b8
    at <anonymous>:wasm-function[2875]:0x39368d
    at <anonymous>:wasm-function[2729]:0x391753
    at <anonymous>:wasm-function[1101]:0x319c55
    at <anonymous>:wasm-function[107]:0xcd755
    at <anonymous>:wasm-function[85]:0x69d1b
    at <anonymous>:wasm-function[3161]:0x39576c
[Info  - 10:15:29 AM] Connection to server got closed. Server will restart.
[Error - 10:15:29 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/user/.vscode/extensions/tamasfe.even-better-toml-0.12.0/dist/extension.js:5570:27)
	at Object.dispose (/Users/user/.vscode/extensions/tamasfe.even-better-toml-0.12.0/dist/extension.js:11022:35)
	at LanguageClient.handleConnectionClosed (/Users/user/.vscode/extensions/tamasfe.even-better-toml-0.12.0/dist/extension.js:13372:42)
	at LanguageClient.handleConnectionClosed (/Users/user/.vscode/extensions/tamasfe.even-better-toml-0.12.0/dist/extension.js:16273:15)
	at closeHandler (/Users/user/.vscode/extensions/tamasfe.even-better-toml-0.12.0/dist/extension.js:13359:18)
	at CallbackList.invoke (/Users/user/.vscode/extensions/tamasfe.even-better-toml-0.12.0/dist/extension.js:3569:39)
	at Emitter.fire (/Users/user/.vscode/extensions/tamasfe.even-better-toml-0.12.0/dist/extension.js:3631:36)
	at closeHandler (/Users/user/.vscode/extensions/tamasfe.even-better-toml-0.12.0/dist/extension.js:4783:26)
	at CallbackList.invoke (/Users/user/.vscode/extensions/tamasfe.even-better-toml-0.12.0/dist/extension.js:3569:39)
	at Emitter.fire (/Users/user/.vscode/extensions/tamasfe.even-better-toml-0.12.0/dist/extension.js:3631:36)
	at IPCMessageReader.fireClose (/Users/user/.vscode/extensions/tamasfe.even-better-toml-0.12.0/dist/extension.js:3780:27)
	at ChildProcess.<anonymous> (/Users/user/.vscode/extensions/tamasfe.even-better-toml-0.12.0/dist/extension.js:5720:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
</code></pre>

### Other Info:
- VSCode version: 1.55.1
- Extension Even Better TOML version: v0.12.0
- Node.js: 12.18.3
- OS: macOS Big Sur 11.2.3

Thanks.

**Comment by tamasfe** [comment]
Thanks, most likely introduced in https://github.com/tamasfe/taplo/commit/59be07d8972a62c7f23d8796c0648f7975c42c9c, I'll fix it asap.

**Comment by tamasfe** [comment]
Should be fixed in the latest extension.

**Comment by Kynson** [comment]
Thanks for the prompt fix! It's working great 👍
